services:
  - type: psql
    name: database
    plan: starter
    region: oregon
    version: 17
    disk:
      size: 1GB
    env:
      - DATABASE_URL

  - type: redis
    name: redis
    plan: free
    region: oregon
    env:
      - REDIS_URL

  - type: web
    name: migrations
    env_vars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
    build:
      dockerfile_path: ./database/Dockerfile
    env: docker
    start_command: "./path/to/migration-command" # команда миграции, например `migrate up`
    deploy:
      wait_for_db: true

  - type: web
    name: api-service
    env_vars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ENV_VAR_FROM_ENV_FILE # добавьте переменные из `.env`
    build:
      dockerfile_path: ./Dockerfile
    env: docker
    start_command: "./path/to/start-command" # команда для запуска API, например `go run main.go`
    ports:
      - 8000
    auto_deploy: true
    deploy:
      wait_for_db: true
